# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        google:
            # must be "google" - it activates that type!
            type: google
            # add and set these environment variables in your .env files
            client_id: "%env(OAUTH_GOOGLE_CLIENT_ID)%"
            client_secret: "%env(OAUTH_GOOGLE_CLIENT_SECRET)%"
            # a route name you'll create
            redirect_route: app_google/connect
            redirect_params: {}
        github:
            # must be "github" - it activates that type!
            type: github
            # add and set these environment variables in your .env files
            client_id: "%env(OAUTH_GITHUB_CLIENT_ID)%"
            client_secret: "%env(OAUTH_GITHUB_CLIENT_SECRET)%"
            # a route name you'll create
            redirect_route: app_github/connect
            redirect_params: {}
